baseURL: https://www.hackwiki.de
languageCode: de-de
title: Hackwiki
theme: hugo-refresh

# This options specify where to look for the images used in this config
# The default value is the "asset" directory of this theme
assetDir: "static"

DefaultContentLanguage: de

## Option to disable additional language in your site.
# disableLanguages: ["ru"]

disableKinds: ["RSS"]

# Option to specify that all links will be open in a new tab.
blackfriday:
  hrefTargetBlank: true

Taxonomies:
  tag: "tags"

# Supported fonts are:
# https://fonts.google.com/

# Icons taken from:
# https://konpa.github.io/devicon/
# https://bulkitv2.cssninja.io/_components-icons-fa.html

params:
  # parameter used to specify the number of article in each row 
  # for the summary pages, the possible options are: 2, 3, 4, 5 or 6
  articlesPerRow: 3

  # option to specify the favicon image of the site
  # the path is relative to the folder "assetDir" of this configuration
  favicon: "/images/favicon.svg"
  jsMinify: true
  cssMinify: true
  cssIntegrity: true
  jsIntegrity: true
  mainColour: "#6495ed"

  summary:
    # option to specify the default image in the summary list
    # the starting folder is configure in "assetDir" of this file
    defaultImage : "/images/default_summary.jpg"

  loading:
    # option to specify the loading image
    # the starting folder is configure in "assetDir" of this file
    image: "/images/loaders/rings.svg"

  mainPage:
    fontFamily: "IBM Plex Sans KR"

  sidebar:
    # option to specify the logo of the sidebar
    # the starting folder is configure in "assetDir" of this file
    logo: "/images/refresh-square.svg"
    # option to specify the font of the sidebar
    fontFamily: "Inter" 

  navbar:
    fontFamily: "Inter"
    showIcons: true

  pagNotFound:
    # option to specify the main picture of the sidebar
    # the starting folder is configure in "assetDir" of this file
    image: "/images/hackwiki_404_klein.png"
    title: 404 Page Not Found :(
    subtitle: This is not the page you were looking for...
    imageWidth: 500px

  homepage:
    linkPosition: "menu+footer"
    linkText: "Startseite"
    title: HACKWIKI
    subtitle:  Persönlicher Blog von Sebastian Feustel
    image: "/images/hackwiki_klein.png"
    imageWidth: 500px

  footer:
    # option to specify the logo in the footer
    # the starting folder is configure in "assetDir" of this file
    logo: "/images/refresh-square.svg"
    email: 
      link: hackwiki2.0@gmail.com
      title: Mail
    linkedin: 
      link: in/sebastian-feustel-842a1a1ab
      title: LinkedIn
    github: 
      link: 53845714nF/hackwiki
      title: Github
    copyright: Sebastian Feustel - 2024

###################################################################
################## multilanguage support options ##################
###################################################################
languages:
  de:
    languageName:       German
    weight:             1
  en:
    languageName:       English
    weight:             2
    # When Specifying different parameters for a different language 
    # you need to specify all the mandatory sub-parameters as well.
    # E.g.: if you specify the "homepage" parameter then you need to
    #       specify all mandatory sub-parameters, e.g.: "title". 
    # See example below:
    params:
      homepage:
        linkPosition: "menu+footer"
        linkText: Homepage
        title: HACKWIKI
        subtitle: Personal blog from Sebastian Feustel
        image: "/images/hackwiki_klein.png" #
        imageWidth: 500px
      
      # Some sub-parameters of the "footer" parameter
      # can be omitted because the code allows for them to be 
      # missed but they will treated as they do not exist,
      # i.e., the parameters of the default language
      # won't be inherited.
      footer:
        logo: "/images/refresh-square.svg"
        email: 
          link: hackwiki2.0@gmail.com
          title: Mail
        linkedin: 
          link: in/sebastian-feustel-842a1a1ab
          title: LinkedIn
        github: 
          link: 53845714nF/hackwiki
          title: Github
        copyright: Sebastian Feustel - 2024
