name: Deploy to GitHub Page (Hackwiki Blog)

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Hugo
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v0.117.0/hugo_0.117.0_Linux-64bit.tar.gz
        tar -xf hugo_0.117.0_Linux-64bit.tar.gz
        mv hugo /usr/local/bin/hugo
        hugo version

    - name: Build Hugo Site
      run: |
        hugo -D
        find public -name "*.html" | xargs  sed -i '4i<meta name="theme-color" content="#6495ed" />'
        

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
