name: Hugo update

on:
  push:
    branches: [ main ]

jobs:
  create:
    name: Create
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hugo install
      run: | 
          apt install hugo
          hugo -D  
          sed -i 's/Myself/Hackwiki/g' public/*.html
          sed -i 's/Myself/Hackwiki/g' public/en/*.html
          find public -name "*.html" | xargs  sed -i '4i<meta name="theme-color" content="#6495ed" />'
          grep -rl Impressum public/ | xargs sed -i 's/Impressum/Danksagung/g'
          cp -R fonts/* public/fonts/
          grep -rl "https://fonts.googleapis.com/css?family=IBM&#43;Plex&#43;Sans&#43;KR" public/ | xargs sed -i 's,https://fonts.googleapis.com/css?family=IBM&#43;Plex&#43;Sans&#43;KR,/fonts/IBM_plex/IBM_Plex.css,g'
          grep -rl "https://fonts.googleapis.com/css?family=Inter" public/ | xargs sed -i 's,https://fonts.googleapis.com/css?family=Inter,/fonts/Inter/Inter.css,g'

    - name: git commit
      run: |
          git config --global user.name 'indexbot_53845714'
          git config --global user.email 'indexbot_53845714@users.noreply.github.com'
          git add public/
          git commit -m "new blog"
          git push
